#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sheep_Wolf.Droid.Resource", IsApplication=true)]

namespace Sheep_Wolf.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int type_animal = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int black = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int blue = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int dark_green = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int gray = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int light_blue = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int light_green = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int white = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int yellow = 2130837511;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030002
			public const int animal_logo = 2130903042;
			
			// aapt resource value: 0x7F030000
			public const int Circle = 2130903040;
			
			// aapt resource value: 0x7F030003
			public const int duck = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int duck_logo = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int hunter = 2130903045;
			
			// aapt resource value: 0x7F030007
			public const int hunter_killer = 2130903047;
			
			// aapt resource value: 0x7F030006
			public const int hunter_kill_wolf = 2130903046;
			
			// aapt resource value: 0x7F030008
			public const int hunter_rip = 2130903048;
			
			// aapt resource value: 0x7F030001
			public const int INFORMATION = 2130903041;
			
			// aapt resource value: 0x7F030009
			public const int killer = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int rip = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int sheep = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int star = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int wolf = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int wolf_kill = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int wolf_kill_hunter = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int wolf_rip = 2130903056;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int addAnimals = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int animalChoice = 2130968577;
			
			// aapt resource value: 0x7F040003
			public const int animalsFoto = 2130968579;
			
			// aapt resource value: 0x7F040002
			public const int animalType = 2130968578;
			
			// aapt resource value: 0x7F040004
			public const int fotoDuck = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int fotoHunter = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int fotoSheep = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int fotoWolf = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int globalLayout = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int imageAnimal = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int listOfAnimals = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int my_toolbar = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int sheeps_container = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int starsLayout = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int textNameOfAnimal = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int textView1 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int textViewDucksNameAdapter = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int textViewHunterNameAdapter = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int textViewNumbSheep = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int textViewSheepsName = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int textViewSheepsNameAdapter = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int textViewWolvesNameAdapter = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int whoKillMe = 2130968598;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int AnimalIDLayout = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int DuckCheckList = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int HunterCheckList = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Main = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int SheepCheckList = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int WolfCheckList = 2131034117;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int Icon = 2131165184;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int animalName = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int desc = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int duckName = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int hunterName = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int nameOfAnimal = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int number = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int sheep = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int sheepName = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int text = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int title = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int titles = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int type = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int wolfName = 2131230733;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
